/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SarkiOnerRouteImport } from './routes/sarki-oner'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSarkilarRouteImport } from './routes/admin.sarkilar'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminKullanicilarRouteImport } from './routes/admin.kullanicilar'
import { Route as AdminCalanRouteImport } from './routes/admin.calan'

const SarkiOnerRoute = SarkiOnerRouteImport.update({
  id: '/sarki-oner',
  path: '/sarki-oner',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSarkilarRoute = AdminSarkilarRouteImport.update({
  id: '/sarkilar',
  path: '/sarkilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKullanicilarRoute = AdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalanRoute = AdminCalanRouteImport.update({
  id: '/calan',
  path: '/calan',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/menu': typeof MenuRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/menu': typeof MenuRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/menu': typeof MenuRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/hakkimizda'
    | '/menu'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sarkilar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hakkimizda'
    | '/menu'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sarkilar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/hakkimizda'
    | '/menu'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/sarkilar'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  MenuRoute: typeof MenuRoute
  SarkiOnerRoute: typeof SarkiOnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sarki-oner': {
      id: '/sarki-oner'
      path: '/sarki-oner'
      fullPath: '/sarki-oner'
      preLoaderRoute: typeof SarkiOnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sarkilar': {
      id: '/admin/sarkilar'
      path: '/sarkilar'
      fullPath: '/admin/sarkilar'
      preLoaderRoute: typeof AdminSarkilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kullanicilar': {
      id: '/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AdminKullanicilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calan': {
      id: '/admin/calan'
      path: '/calan'
      fullPath: '/admin/calan'
      preLoaderRoute: typeof AdminCalanRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalanRoute: typeof AdminCalanRoute
  AdminKullanicilarRoute: typeof AdminKullanicilarRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminSarkilarRoute: typeof AdminSarkilarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalanRoute: AdminCalanRoute,
  AdminKullanicilarRoute: AdminKullanicilarRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminSarkilarRoute: AdminSarkilarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  MenuRoute: MenuRoute,
  SarkiOnerRoute: SarkiOnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
