/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleSarkiOnerRouteImport } from './routes/$locale.sarki-oner'
import { Route as LocaleMenuRouteImport } from './routes/$locale.menu'
import { Route as LocaleHakkimizdaRouteImport } from './routes/$locale.hakkimizda'
import { Route as LocaleAuthRouteImport } from './routes/$locale.auth'
import { Route as LocaleAdminRouteImport } from './routes/$locale.admin'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale.admin.index'
import { Route as LocaleAdminSarkilarRouteImport } from './routes/$locale.admin.sarkilar'
import { Route as LocaleAdminMenuRouteImport } from './routes/$locale.admin.menu'
import { Route as LocaleAdminKullanicilarRouteImport } from './routes/$locale.admin.kullanicilar'
import { Route as LocaleAdminCalanRouteImport } from './routes/$locale.admin.calan'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSarkiOnerRoute = LocaleSarkiOnerRouteImport.update({
  id: '/sarki-oner',
  path: '/sarki-oner',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMenuRoute = LocaleMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHakkimizdaRoute = LocaleHakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthRoute = LocaleAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminSarkilarRoute = LocaleAdminSarkilarRouteImport.update({
  id: '/sarkilar',
  path: '/sarkilar',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminMenuRoute = LocaleAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminKullanicilarRoute = LocaleAdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminCalanRoute = LocaleAdminCalanRouteImport.update({
  id: '/calan',
  path: '/calan',
  getParentRoute: () => LocaleAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/hakkimizda': typeof LocaleHakkimizdaRoute
  '/$locale/menu': typeof LocaleMenuRoute
  '/$locale/sarki-oner': typeof LocaleSarkiOnerRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/calan': typeof LocaleAdminCalanRoute
  '/$locale/admin/kullanicilar': typeof LocaleAdminKullanicilarRoute
  '/$locale/admin/menu': typeof LocaleAdminMenuRoute
  '/$locale/admin/sarkilar': typeof LocaleAdminSarkilarRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/hakkimizda': typeof LocaleHakkimizdaRoute
  '/$locale/menu': typeof LocaleMenuRoute
  '/$locale/sarki-oner': typeof LocaleSarkiOnerRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/calan': typeof LocaleAdminCalanRoute
  '/$locale/admin/kullanicilar': typeof LocaleAdminKullanicilarRoute
  '/$locale/admin/menu': typeof LocaleAdminMenuRoute
  '/$locale/admin/sarkilar': typeof LocaleAdminSarkilarRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/hakkimizda': typeof LocaleHakkimizdaRoute
  '/$locale/menu': typeof LocaleMenuRoute
  '/$locale/sarki-oner': typeof LocaleSarkiOnerRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/calan': typeof LocaleAdminCalanRoute
  '/$locale/admin/kullanicilar': typeof LocaleAdminKullanicilarRoute
  '/$locale/admin/menu': typeof LocaleAdminMenuRoute
  '/$locale/admin/sarkilar': typeof LocaleAdminSarkilarRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/auth'
    | '/$locale/hakkimizda'
    | '/$locale/menu'
    | '/$locale/sarki-oner'
    | '/$locale/'
    | '/$locale/admin/calan'
    | '/$locale/admin/kullanicilar'
    | '/$locale/admin/menu'
    | '/$locale/admin/sarkilar'
    | '/$locale/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/auth'
    | '/$locale/hakkimizda'
    | '/$locale/menu'
    | '/$locale/sarki-oner'
    | '/$locale'
    | '/$locale/admin/calan'
    | '/$locale/admin/kullanicilar'
    | '/$locale/admin/menu'
    | '/$locale/admin/sarkilar'
    | '/$locale/admin'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/auth'
    | '/$locale/hakkimizda'
    | '/$locale/menu'
    | '/$locale/sarki-oner'
    | '/$locale/'
    | '/$locale/admin/calan'
    | '/$locale/admin/kullanicilar'
    | '/$locale/admin/menu'
    | '/$locale/admin/sarkilar'
    | '/$locale/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sarki-oner': {
      id: '/$locale/sarki-oner'
      path: '/sarki-oner'
      fullPath: '/$locale/sarki-oner'
      preLoaderRoute: typeof LocaleSarkiOnerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/menu': {
      id: '/$locale/menu'
      path: '/menu'
      fullPath: '/$locale/menu'
      preLoaderRoute: typeof LocaleMenuRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/hakkimizda': {
      id: '/$locale/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/$locale/hakkimizda'
      preLoaderRoute: typeof LocaleHakkimizdaRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/sarkilar': {
      id: '/$locale/admin/sarkilar'
      path: '/sarkilar'
      fullPath: '/$locale/admin/sarkilar'
      preLoaderRoute: typeof LocaleAdminSarkilarRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/menu': {
      id: '/$locale/admin/menu'
      path: '/menu'
      fullPath: '/$locale/admin/menu'
      preLoaderRoute: typeof LocaleAdminMenuRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/kullanicilar': {
      id: '/$locale/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/$locale/admin/kullanicilar'
      preLoaderRoute: typeof LocaleAdminKullanicilarRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/calan': {
      id: '/$locale/admin/calan'
      path: '/calan'
      fullPath: '/$locale/admin/calan'
      preLoaderRoute: typeof LocaleAdminCalanRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminCalanRoute: typeof LocaleAdminCalanRoute
  LocaleAdminKullanicilarRoute: typeof LocaleAdminKullanicilarRoute
  LocaleAdminMenuRoute: typeof LocaleAdminMenuRoute
  LocaleAdminSarkilarRoute: typeof LocaleAdminSarkilarRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminCalanRoute: LocaleAdminCalanRoute,
  LocaleAdminKullanicilarRoute: LocaleAdminKullanicilarRoute,
  LocaleAdminMenuRoute: LocaleAdminMenuRoute,
  LocaleAdminSarkilarRoute: LocaleAdminSarkilarRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleAuthRoute: typeof LocaleAuthRoute
  LocaleHakkimizdaRoute: typeof LocaleHakkimizdaRoute
  LocaleMenuRoute: typeof LocaleMenuRoute
  LocaleSarkiOnerRoute: typeof LocaleSarkiOnerRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleAuthRoute: LocaleAuthRoute,
  LocaleHakkimizdaRoute: LocaleHakkimizdaRoute,
  LocaleMenuRoute: LocaleMenuRoute,
  LocaleSarkiOnerRoute: LocaleSarkiOnerRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
