/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SarkiOnerRouteImport } from './routes/sarki-oner'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KasguideRouteImport } from './routes/kasguide'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as DragomandoRouteImport } from './routes/dragomando'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EnSarkiOnerRouteImport } from './routes/en.sarki-oner'
import { Route as EnProgramRouteImport } from './routes/en.program'
import { Route as EnMenuRouteImport } from './routes/en.menu'
import { Route as EnKasguideRouteImport } from './routes/en.kasguide'
import { Route as EnHakkimizdaRouteImport } from './routes/en.hakkimizda'
import { Route as EnDragomandoRouteImport } from './routes/en.dragomando'
import { Route as AdminSosyalMedyaRouteImport } from './routes/admin.sosyal-medya'
import { Route as AdminSarkilarRouteImport } from './routes/admin.sarkilar'
import { Route as AdminProgramRouteImport } from './routes/admin.program'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminKullanicilarRouteImport } from './routes/admin.kullanicilar'
import { Route as AdminKartlarRouteImport } from './routes/admin.kartlar'
import { Route as AdminDegerlendirmelerRouteImport } from './routes/admin.degerlendirmeler'
import { Route as AdminCalanRouteImport } from './routes/admin.calan'

const SarkiOnerRoute = SarkiOnerRouteImport.update({
  id: '/sarki-oner',
  path: '/sarki-oner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KasguideRoute = KasguideRouteImport.update({
  id: '/kasguide',
  path: '/kasguide',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const DragomandoRoute = DragomandoRouteImport.update({
  id: '/dragomando',
  path: '/dragomando',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EnSarkiOnerRoute = EnSarkiOnerRouteImport.update({
  id: '/en/sarki-oner',
  path: '/en/sarki-oner',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProgramRoute = EnProgramRouteImport.update({
  id: '/en/program',
  path: '/en/program',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMenuRoute = EnMenuRouteImport.update({
  id: '/en/menu',
  path: '/en/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKasguideRoute = EnKasguideRouteImport.update({
  id: '/en/kasguide',
  path: '/en/kasguide',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHakkimizdaRoute = EnHakkimizdaRouteImport.update({
  id: '/en/hakkimizda',
  path: '/en/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDragomandoRoute = EnDragomandoRouteImport.update({
  id: '/en/dragomando',
  path: '/en/dragomando',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSosyalMedyaRoute = AdminSosyalMedyaRouteImport.update({
  id: '/sosyal-medya',
  path: '/sosyal-medya',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSarkilarRoute = AdminSarkilarRouteImport.update({
  id: '/sarkilar',
  path: '/sarkilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramRoute = AdminProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKullanicilarRoute = AdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKartlarRoute = AdminKartlarRouteImport.update({
  id: '/kartlar',
  path: '/kartlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDegerlendirmelerRoute = AdminDegerlendirmelerRouteImport.update({
  id: '/degerlendirmeler',
  path: '/degerlendirmeler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalanRoute = AdminCalanRouteImport.update({
  id: '/calan',
  path: '/calan',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dragomando': typeof DragomandoRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kasguide': typeof KasguideRoute
  '/menu': typeof MenuRoute
  '/program': typeof ProgramRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/degerlendirmeler': typeof AdminDegerlendirmelerRoute
  '/admin/kartlar': typeof AdminKartlarRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin/sosyal-medya': typeof AdminSosyalMedyaRoute
  '/en/dragomando': typeof EnDragomandoRoute
  '/en/hakkimizda': typeof EnHakkimizdaRoute
  '/en/kasguide': typeof EnKasguideRoute
  '/en/menu': typeof EnMenuRoute
  '/en/program': typeof EnProgramRoute
  '/en/sarki-oner': typeof EnSarkiOnerRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dragomando': typeof DragomandoRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kasguide': typeof KasguideRoute
  '/menu': typeof MenuRoute
  '/program': typeof ProgramRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/degerlendirmeler': typeof AdminDegerlendirmelerRoute
  '/admin/kartlar': typeof AdminKartlarRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin/sosyal-medya': typeof AdminSosyalMedyaRoute
  '/en/dragomando': typeof EnDragomandoRoute
  '/en/hakkimizda': typeof EnHakkimizdaRoute
  '/en/kasguide': typeof EnKasguideRoute
  '/en/menu': typeof EnMenuRoute
  '/en/program': typeof EnProgramRoute
  '/en/sarki-oner': typeof EnSarkiOnerRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dragomando': typeof DragomandoRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kasguide': typeof KasguideRoute
  '/menu': typeof MenuRoute
  '/program': typeof ProgramRoute
  '/sarki-oner': typeof SarkiOnerRoute
  '/admin/calan': typeof AdminCalanRoute
  '/admin/degerlendirmeler': typeof AdminDegerlendirmelerRoute
  '/admin/kartlar': typeof AdminKartlarRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/program': typeof AdminProgramRoute
  '/admin/sarkilar': typeof AdminSarkilarRoute
  '/admin/sosyal-medya': typeof AdminSosyalMedyaRoute
  '/en/dragomando': typeof EnDragomandoRoute
  '/en/hakkimizda': typeof EnHakkimizdaRoute
  '/en/kasguide': typeof EnKasguideRoute
  '/en/menu': typeof EnMenuRoute
  '/en/program': typeof EnProgramRoute
  '/en/sarki-oner': typeof EnSarkiOnerRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dragomando'
    | '/hakkimizda'
    | '/kasguide'
    | '/menu'
    | '/program'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/degerlendirmeler'
    | '/admin/kartlar'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/program'
    | '/admin/sarkilar'
    | '/admin/sosyal-medya'
    | '/en/dragomando'
    | '/en/hakkimizda'
    | '/en/kasguide'
    | '/en/menu'
    | '/en/program'
    | '/en/sarki-oner'
    | '/admin/'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dragomando'
    | '/hakkimizda'
    | '/kasguide'
    | '/menu'
    | '/program'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/degerlendirmeler'
    | '/admin/kartlar'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/program'
    | '/admin/sarkilar'
    | '/admin/sosyal-medya'
    | '/en/dragomando'
    | '/en/hakkimizda'
    | '/en/kasguide'
    | '/en/menu'
    | '/en/program'
    | '/en/sarki-oner'
    | '/admin'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dragomando'
    | '/hakkimizda'
    | '/kasguide'
    | '/menu'
    | '/program'
    | '/sarki-oner'
    | '/admin/calan'
    | '/admin/degerlendirmeler'
    | '/admin/kartlar'
    | '/admin/kullanicilar'
    | '/admin/menu'
    | '/admin/program'
    | '/admin/sarkilar'
    | '/admin/sosyal-medya'
    | '/en/dragomando'
    | '/en/hakkimizda'
    | '/en/kasguide'
    | '/en/menu'
    | '/en/program'
    | '/en/sarki-oner'
    | '/admin/'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DragomandoRoute: typeof DragomandoRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  KasguideRoute: typeof KasguideRoute
  MenuRoute: typeof MenuRoute
  ProgramRoute: typeof ProgramRoute
  SarkiOnerRoute: typeof SarkiOnerRoute
  EnDragomandoRoute: typeof EnDragomandoRoute
  EnHakkimizdaRoute: typeof EnHakkimizdaRoute
  EnKasguideRoute: typeof EnKasguideRoute
  EnMenuRoute: typeof EnMenuRoute
  EnProgramRoute: typeof EnProgramRoute
  EnSarkiOnerRoute: typeof EnSarkiOnerRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sarki-oner': {
      id: '/sarki-oner'
      path: '/sarki-oner'
      fullPath: '/sarki-oner'
      preLoaderRoute: typeof SarkiOnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasguide': {
      id: '/kasguide'
      path: '/kasguide'
      fullPath: '/kasguide'
      preLoaderRoute: typeof KasguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragomando': {
      id: '/dragomando'
      path: '/dragomando'
      fullPath: '/dragomando'
      preLoaderRoute: typeof DragomandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/sarki-oner': {
      id: '/en/sarki-oner'
      path: '/en/sarki-oner'
      fullPath: '/en/sarki-oner'
      preLoaderRoute: typeof EnSarkiOnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/program': {
      id: '/en/program'
      path: '/en/program'
      fullPath: '/en/program'
      preLoaderRoute: typeof EnProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/menu': {
      id: '/en/menu'
      path: '/en/menu'
      fullPath: '/en/menu'
      preLoaderRoute: typeof EnMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kasguide': {
      id: '/en/kasguide'
      path: '/en/kasguide'
      fullPath: '/en/kasguide'
      preLoaderRoute: typeof EnKasguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/hakkimizda': {
      id: '/en/hakkimizda'
      path: '/en/hakkimizda'
      fullPath: '/en/hakkimizda'
      preLoaderRoute: typeof EnHakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/dragomando': {
      id: '/en/dragomando'
      path: '/en/dragomando'
      fullPath: '/en/dragomando'
      preLoaderRoute: typeof EnDragomandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sosyal-medya': {
      id: '/admin/sosyal-medya'
      path: '/sosyal-medya'
      fullPath: '/admin/sosyal-medya'
      preLoaderRoute: typeof AdminSosyalMedyaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sarkilar': {
      id: '/admin/sarkilar'
      path: '/sarkilar'
      fullPath: '/admin/sarkilar'
      preLoaderRoute: typeof AdminSarkilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/program': {
      id: '/admin/program'
      path: '/program'
      fullPath: '/admin/program'
      preLoaderRoute: typeof AdminProgramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kullanicilar': {
      id: '/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AdminKullanicilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kartlar': {
      id: '/admin/kartlar'
      path: '/kartlar'
      fullPath: '/admin/kartlar'
      preLoaderRoute: typeof AdminKartlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/degerlendirmeler': {
      id: '/admin/degerlendirmeler'
      path: '/degerlendirmeler'
      fullPath: '/admin/degerlendirmeler'
      preLoaderRoute: typeof AdminDegerlendirmelerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calan': {
      id: '/admin/calan'
      path: '/calan'
      fullPath: '/admin/calan'
      preLoaderRoute: typeof AdminCalanRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalanRoute: typeof AdminCalanRoute
  AdminDegerlendirmelerRoute: typeof AdminDegerlendirmelerRoute
  AdminKartlarRoute: typeof AdminKartlarRoute
  AdminKullanicilarRoute: typeof AdminKullanicilarRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminProgramRoute: typeof AdminProgramRoute
  AdminSarkilarRoute: typeof AdminSarkilarRoute
  AdminSosyalMedyaRoute: typeof AdminSosyalMedyaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalanRoute: AdminCalanRoute,
  AdminDegerlendirmelerRoute: AdminDegerlendirmelerRoute,
  AdminKartlarRoute: AdminKartlarRoute,
  AdminKullanicilarRoute: AdminKullanicilarRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminProgramRoute: AdminProgramRoute,
  AdminSarkilarRoute: AdminSarkilarRoute,
  AdminSosyalMedyaRoute: AdminSosyalMedyaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DragomandoRoute: DragomandoRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  KasguideRoute: KasguideRoute,
  MenuRoute: MenuRoute,
  ProgramRoute: ProgramRoute,
  SarkiOnerRoute: SarkiOnerRoute,
  EnDragomandoRoute: EnDragomandoRoute,
  EnHakkimizdaRoute: EnHakkimizdaRoute,
  EnKasguideRoute: EnKasguideRoute,
  EnMenuRoute: EnMenuRoute,
  EnProgramRoute: EnProgramRoute,
  EnSarkiOnerRoute: EnSarkiOnerRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
