-- Sync menu_items with NEWMENU.pdf (2026 price update)
delete from public.menu_items;

insert into public.menu_items (
  name,
  name_en,
  description,
  description_en,
  price,
  category,
  image_url,
  tags,
  tags_en,
  details,
  is_available,
  sort_order
)
values
  -- Beers
  ('Efes Pilsen Draft','Efes Pilsen Draft','Draft beer. 33 cl: ₺225 / 50 cl: ₺325.','Draft beer. 33 cl: ₺225 / 50 cl: ₺325.',225,'beers',null,array['draft'],array['draft'],'{"priceLabel":"33 cl: ₺225 / 50 cl: ₺325"}'::jsonb,true,10),
  ('Efes Pilsen Take Away','Efes Pilsen Take Away','Take away draft. 40 cl: ₺240. Glass deposit: ₺20.','Take away draft. 40 cl: ₺240. Glass deposit: ₺20.',240,'beers',null,array['take away'],array['take away'],'{"priceLabel":"40 cl: ₺240 / glass deposit: ₺20"}'::jsonb,true,20),
  ('Efes Pilsen','Efes Pilsen','Bottle beer. 30 cl: ₺300 / 50 cl: ₺350.','Bottle beer. 30 cl: ₺300 / 50 cl: ₺350.',300,'beers',null,array['bottle'],array['bottle'],'{"priceLabel":"30 cl: ₺300 / 50 cl: ₺350"}'::jsonb,true,30),
  ('Efes Malt','Efes Malt','Bottle beer. 50 cl.','Bottle beer. 50 cl.',350,'beers',null,array['bottle'],array['bottle'],'{"priceLabel":"50 cl: ₺350"}'::jsonb,true,40),
  ('Efes Green','Efes Green','Bottle beer. 50 cl.','Bottle beer. 50 cl.',370,'beers',null,array['bottle'],array['bottle'],'{"priceLabel":"50 cl: ₺370"}'::jsonb,true,50),
  ('Efes Glutenfree','Efes Glutenfree','Bottle beer. 50 cl.','Bottle beer. 50 cl.',470,'beers',null,array['gluten free'],array['gluten free'],'{"priceLabel":"50 cl: ₺470"}'::jsonb,true,60),
  ('Bomonti Unfiltered','Bomonti Unfiltered','Bottle beer. 50 cl.','Bottle beer. 50 cl.',390,'beers',null,array['unfiltered'],array['unfiltered'],'{"priceLabel":"50 cl: ₺390"}'::jsonb,true,70),
  ('Becks','Becks','Bottle beer. 33 cl.','Bottle beer. 33 cl.',350,'beers',null,array['lager'],array['lager'],'{"priceLabel":"33 cl: ₺350"}'::jsonb,true,80),
  ('Bud','Bud','Bottle beer. 33 cl.','Bottle beer. 33 cl.',350,'beers',null,array['lager'],array['lager'],'{"priceLabel":"33 cl: ₺350"}'::jsonb,true,90),
  ('Stella','Stella','Bottle beer. 44 cl.','Bottle beer. 44 cl.',420,'beers',null,array['lager'],array['lager'],'{"priceLabel":"44 cl: ₺420"}'::jsonb,true,100),
  ('Corona','Corona','Bottle beer. 33 cl.','Bottle beer. 33 cl.',520,'beers',null,array['lager'],array['lager'],'{"priceLabel":"33 cl: ₺520"}'::jsonb,true,110),
  ('IPA Summer Gara Guzu','IPA Summer Gara Guzu','Bottle beer. 33 cl.','Bottle beer. 33 cl.',540,'beers',null,array['ipa'],array['ipa'],'{"priceLabel":"33 cl: ₺540"}'::jsonb,true,120),
  ('Duvel','Duvel','Bottle beer. 33 cl.','Bottle beer. 33 cl.',690,'beers',null,array['strong ale'],array['strong ale'],'{"priceLabel":"33 cl: ₺690"}'::jsonb,true,130),
  ('Peja (Alcoholfree)','Peja (Alcoholfree)','Alcohol-free beer. 33 cl.','Alcohol-free beer. 33 cl.',220,'beers',null,array['alcohol free'],array['alcohol free'],'{"priceLabel":"33 cl: ₺220"}'::jsonb,true,140),

  -- Non Alcoholics
  ('Coca Cola','Coca Cola',null,null,150,'non_alcoholics',null,array['soft drink'],array['soft drink'],null,true,210),
  ('Coca Cola Zero','Coca Cola Zero',null,null,150,'non_alcoholics',null,array['soft drink'],array['soft drink'],null,true,220),
  ('Sprite','Sprite',null,null,150,'non_alcoholics',null,array['soft drink'],array['soft drink'],null,true,230),
  ('Schweppes Tonic','Schweppes Tonic',null,null,100,'non_alcoholics',null,array['mixer'],array['mixer'],null,true,240),
  ('Sparkling Water','Sparkling Water',null,null,100,'non_alcoholics',null,array['water'],array['water'],null,true,250),
  ('Bottled Water','Bottled Water',null,null,100,'non_alcoholics',null,array['water'],array['water'],null,true,260),
  ('Cappy Fruit Juices','Cappy Fruit Juices',null,null,150,'non_alcoholics',null,array['juice'],array['juice'],null,true,270),
  ('Fresh Orange Juice','Fresh Orange Juice',null,null,260,'non_alcoholics',null,array['fresh'],array['fresh'],null,true,280),
  ('Homemade Ice Tea (peach)','Homemade Ice Tea (peach)',null,null,220,'non_alcoholics',null,array['homemade'],array['homemade'],null,true,290),
  ('Homemade Lemonade','Homemade Lemonade',null,null,260,'non_alcoholics',null,array['homemade'],array['homemade'],null,true,300),

  -- Coffee
  ('Espresso','Espresso',null,null,120,'coffee',null,array['coffee'],array['coffee'],null,true,410),
  ('Double Espresso','Double Espresso',null,null,200,'coffee',null,array['coffee'],array['coffee'],null,true,420),
  ('Americano','Americano',null,null,220,'coffee',null,array['coffee'],array['coffee'],null,true,430),
  ('Cappuccino','Cappuccino',null,null,260,'coffee',null,array['coffee'],array['coffee'],null,true,440),
  ('Latte','Latte',null,null,260,'coffee',null,array['coffee'],array['coffee'],null,true,450),
  ('Turkish Coffee','Turkish Coffee',null,null,140,'coffee',null,array['coffee'],array['coffee'],null,true,460),
  ('Irish Coffee (with Jameson)','Irish Coffee (with Jameson)',null,null,550,'coffee',null,array['coffee'],array['coffee'],null,true,470),

  -- Wines
  (
    'Vinkara Quattro White',
    'Vinkara Quattro White',
    'Narince, Hasandede and Emir. Fruity, rich and easy drinking with a strong acidity.',
    'Narince, Hasandede and Emir. Fruity, rich and easy drinking with a strong acidity.',
    350,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"Glass: ₺350 / 70 cl: ₺1250"}'::jsonb,
    true,
    510
  ),
  (
    'Paşaeli SYS White',
    'Paşaeli SYS White',
    'Sultaniye, Yapıncak and Sıdalan. 3 months rest. On the nose lemon, green apple and honeysuckle.',
    'Sultaniye, Yapıncak and Sıdalan. 3 months rest. On the nose lemon, green apple and honeysuckle.',
    550,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"Glass: ₺550 / 70 cl: ₺2100"}'::jsonb,
    true,
    520
  ),
  (
    'Porta Diverti Sauvignon Blanc',
    'Porta Diverti Sauvignon Blanc',
    'Scents of minerals and citrus. Very crisp and fruity on the palate with a lengthy finish.',
    'Scents of minerals and citrus. Very crisp and fruity on the palate with a lengthy finish.',
    2750,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    530
  ),
  (
    'Vinkara Quattro Rose',
    'Vinkara Quattro Rose',
    'Kalecik Karası and Aleatico. Dry with scents of rose and lime from the Aleatico and lively flavours of red fruits.',
    'Kalecik Karası and Aleatico. Dry with scents of rose and lime from the Aleatico and lively flavours of red fruits.',
    550,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"Glass: ₺550 / 70 cl: ₺2100"}'::jsonb,
    true,
    540
  ),
  (
    'Paşaeli Çalkarası Blush',
    'Paşaeli Çalkarası Blush',
    'Çalkarası. Fermented in stainless steel tanks and aged on the lees for 3 months. On the nose wild strawberry, raspberry and thyme.',
    'Çalkarası. Fermented in stainless steel tanks and aged on the lees for 3 months. On the nose wild strawberry, raspberry and thyme.',
    550,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"Glass: ₺550 / 70 cl: ₺2100"}'::jsonb,
    true,
    550
  ),
  (
    'Porta Diverti Rose',
    'Porta Diverti Rose',
    'Merlot. Fermented in steel tanks. Scents of red fruits and rose jam. Lively with a rich, long finish.',
    'Merlot. Fermented in steel tanks. Scents of red fruits and rose jam. Lively with a rich, long finish.',
    2750,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    560
  ),
  (
    'Vinkara Quattro Red',
    'Vinkara Quattro Red',
    'Öküzgözü, Boğazkere and Alicante. On the nose plum, cherry and pepper. Dry, with mild tannins and a long finish.',
    'Öküzgözü, Boğazkere and Alicante. On the nose plum, cherry and pepper. Dry, with mild tannins and a long finish.',
    350,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"Glass: ₺350 / 70 cl: ₺1250"}'::jsonb,
    true,
    570
  ),
  (
    'Paşaeli CSKS Red',
    'Paşaeli CSKS Red',
    'Cabernet Sauvignon and Karasakız, from around 25 years old vines. Aged in oak barrels for 3 months. On the nose sour cherry and bramble.',
    'Cabernet Sauvignon and Karasakız, from around 25 years old vines. Aged in oak barrels for 3 months. On the nose sour cherry and bramble.',
    550,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"Glass: ₺550 / 70 cl: ₺2100"}'::jsonb,
    true,
    580
  ),
  (
    'Porta Diverti Red',
    'Porta Diverti Red',
    'Cabernet Sauvignon, Cabernet Franc, Merlot and Petit Verdot. Aged in oak barrels. Limited filtration. On the nose ripe fruits, tobacco and chocolate.',
    'Cabernet Sauvignon, Cabernet Franc, Merlot and Petit Verdot. Aged in oak barrels. Limited filtration. On the nose ripe fruits, tobacco and chocolate.',
    2750,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    590
  ),

  -- Signatures
  ('Garden Fairy','Garden Fairy','Smirnoff Vodka, Sour Apple Liqueur, Sour Apple Juice, Lemon Juice, Mint Mixer, Fresh Mint.','Smirnoff Vodka, Sour Apple Liqueur, Sour Apple Juice, Lemon Juice, Mint Mixer, Fresh Mint.',850,'signatures',null,array['signature'],array['signature'],null,true,710),
  ('Jamal Libre','Jamal Libre','C. Morgan Spiced Rum, Coke, Muddled Lime.','C. Morgan Spiced Rum, Coke, Muddled Lime.',850,'signatures',null,array['signature'],array['signature'],null,true,720),
  ('Our Garden''s Sorrel','Our Garden''s Sorrel','Beefeater Gin, Special Sorrel Mix.','Beefeater Gin, Special Sorrel Mix.',900,'signatures',null,array['signature'],array['signature'],null,true,730),
  ('Botanique','Botanique','Beefeater Gin, Basil Mix, Lemon Juice, Cucumber, Rosemary.','Beefeater Gin, Basil Mix, Lemon Juice, Cucumber, Rosemary.',900,'signatures',null,array['signature'],array['signature'],null,true,740),
  ('Sour Almond','Sour Almond','Disoranno, Jack Daniel''s, Lemon Juice.','Disoranno, Jack Daniel''s, Lemon Juice.',850,'signatures',null,array['signature'],array['signature'],null,true,750),

  -- Cocktails
  ('Gin Fizz','Gin Fizz',null,null,700,'cocktails',null,array['classic'],array['classic'],null,true,810),
  ('Million Dollar','Million Dollar',null,null,750,'cocktails',null,array['classic'],array['classic'],null,true,820),
  ('Green Ghost','Green Ghost',null,null,850,'cocktails',null,array['classic'],array['classic'],null,true,830),
  ('The Jasmine','The Jasmine',null,null,850,'cocktails',null,array['classic'],array['classic'],null,true,840),
  ('Negroni','Negroni',null,null,800,'cocktails',null,array['classic'],array['classic'],null,true,850),
  ('Cosmopolitan','Cosmopolitan',null,null,750,'cocktails',null,array['classic'],array['classic'],null,true,860),
  ('Porn Star Martini','Porn Star Martini',null,null,850,'cocktails',null,array['martini'],array['martini'],null,true,870),
  ('Espresso Martini','Espresso Martini',null,null,800,'cocktails',null,array['martini'],array['martini'],null,true,880),
  ('Bloody Mary','Bloody Mary',null,null,800,'cocktails',null,array['classic'],array['classic'],null,true,890),
  ('Mojito','Mojito',null,null,800,'cocktails',null,array['classic'],array['classic'],null,true,900),
  ('Strawberry Daiquiri (Frozen)','Strawberry Daiquiri (Frozen)',null,null,800,'cocktails',null,array['frozen'],array['frozen'],null,true,910),
  ('Bahama Mama','Bahama Mama',null,null,800,'cocktails',null,array['tropical'],array['tropical'],null,true,920),
  ('Margarita','Margarita',null,null,800,'cocktails',null,array['classic'],array['classic'],null,true,930),
  ('Chili Passion Margarita','Chili Passion Margarita',null,null,800,'cocktails',null,array['spicy'],array['spicy'],null,true,940),
  ('Whiskey Sour','Whiskey Sour',null,null,850,'cocktails',null,array['classic'],array['classic'],null,true,950),
  ('Old Fashioned','Old Fashioned',null,null,850,'cocktails',null,array['classic'],array['classic'],null,true,960),
  ('Boulevardier','Boulevardier',null,null,850,'cocktails',null,array['classic'],array['classic'],null,true,970),

  -- Spritzes
  ('Aperol Spritz','Aperol Spritz',null,null,750,'spritzes',null,array['spritz'],array['spritz'],null,true,1010),
  ('Garden Spritz','Garden Spritz',null,null,750,'spritzes',null,array['spritz'],array['spritz'],null,true,1020),
  ('Campari Spritz','Campari Spritz',null,null,750,'spritzes',null,array['spritz'],array['spritz'],null,true,1030),
  ('Limoncello Spritz','Limoncello Spritz',null,null,750,'spritzes',null,array['spritz'],array['spritz'],null,true,1040),
  ('Hugo','Hugo',null,null,800,'spritzes',null,array['spritz'],array['spritz'],null,true,1050),

  -- Spirits
  ('Gordon''s','Gordon''s','Gin.','Gin.',400,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺400 / Double: ₺650"}'::jsonb,true,1110),
  ('Beefeater','Beefeater','Gin.','Gin.',450,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺450 / Double: ₺750"}'::jsonb,true,1120),
  ('Bombay Sapphire','Bombay Sapphire','Gin.','Gin.',550,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1130),
  ('Hendrick''s','Hendrick''s','Gin.','Gin.',750,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺750 / Double: ₺1150"}'::jsonb,true,1140),
  ('Smirnoff','Smirnoff','Vodka.','Vodka.',400,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺400 / Double: ₺600"}'::jsonb,true,1150),
  ('Absolut','Absolut','Vodka.','Vodka.',450,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺450 / Double: ₺750"}'::jsonb,true,1160),
  ('Belvedere','Belvedere','Vodka.','Vodka.',750,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺750 / Double: ₺1150"}'::jsonb,true,1170),
  ('C. Morgan Spiced','C. Morgan Spiced','Rum.','Rum.',350,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺350 / Double: ₺550"}'::jsonb,true,1180),
  ('Negrita Dark','Negrita Dark','Rum.','Rum.',350,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺350 / Double: ₺550"}'::jsonb,true,1190),
  ('Havana Club 3 Años','Havana Club 3 Años','Rum.','Rum.',450,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺450 / Double: ₺650"}'::jsonb,true,1200),
  ('Zacapa','Zacapa','Rum.','Rum.',550,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1210),
  ('Sierra Blanco','Sierra Blanco','Tequila.','Tequila.',400,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺400 / Double: ₺650"}'::jsonb,true,1220),
  ('Olmeca Gold','Olmeca Gold','Tequila.','Tequila.',450,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺450 / Double: ₺750"}'::jsonb,true,1230),
  ('Don Julio Blanco','Don Julio Blanco','Tequila.','Tequila.',650,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺650 / Double: ₺990"}'::jsonb,true,1240),
  ('Patron Reposado','Patron Reposado','Tequila.','Tequila.',750,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺750 / Double: ₺1150"}'::jsonb,true,1250),
  ('Jim Beam','Jim Beam','Whiskey.','Whiskey.',550,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1260),
  ('Jack Daniel''s','Jack Daniel''s','Whiskey.','Whiskey.',550,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1270),
  ('Jameson','Jameson','Whiskey.','Whiskey.',550,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1280),
  ('Famous Grouse','Famous Grouse','Whiskey.','Whiskey.',450,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺450 / Double: ₺650"}'::jsonb,true,1290),
  ('Johnnie Walker Black Label','Johnnie Walker Black Label','Whiskey.','Whiskey.',550,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1300),
  ('Glenfiddich 12','Glenfiddich 12','Whiskey.','Whiskey.',700,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺700 / Double: ₺1100"}'::jsonb,true,1310),
  ('Talisker','Talisker','Whiskey.','Whiskey.',800,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺800 / Double: ₺1200"}'::jsonb,true,1320),
  ('Lagavulin','Lagavulin','Whiskey.','Whiskey.',800,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺800 / Double: ₺1200"}'::jsonb,true,1330),
  ('Napoleon Apollon','Napoleon Apollon','Brandy.','Brandy.',400,'spirits',null,array['brandy'],array['brandy'],'{"priceLabel":"Single: ₺400 / Double: ₺650"}'::jsonb,true,1340),
  ('Metaxa 7 Stars','Metaxa 7 Stars','Brandy.','Brandy.',650,'spirits',null,array['brandy'],array['brandy'],'{"priceLabel":"Single: ₺650 / Double: ₺990"}'::jsonb,true,1350),
  ('Hennessy VS','Hennessy VS','Cognac.','Cognac.',650,'spirits',null,array['cognac'],array['cognac'],'{"priceLabel":"Single: ₺650 / Double: ₺990"}'::jsonb,true,1360),
  ('Rémy Martin VSOP','Rémy Martin VSOP','Cognac.','Cognac.',790,'spirits',null,array['cognac'],array['cognac'],'{"priceLabel":"Single: ₺790 / Double: ₺1190"}'::jsonb,true,1370),
  ('Baileys','Baileys','Liqueur.','Liqueur.',350,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺350 / Double: ₺550"}'::jsonb,true,1380),
  ('Archers','Archers','Liqueur.','Liqueur.',450,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺450 / Double: ₺650"}'::jsonb,true,1390),
  ('Cointreau','Cointreau','Liqueur.','Liqueur.',550,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺550 / Double: ₺850"}'::jsonb,true,1400),
  ('Martini Bianco','Martini Bianco','Liqueur.','Liqueur.',350,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺350 / Double: ₺550"}'::jsonb,true,1410),
  ('Disaronno','Disaronno','Liqueur.','Liqueur.',450,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺450 / Double: ₺700"}'::jsonb,true,1420),
  ('Göbek Rakı','Göbek Rakı','Liqueur.','Liqueur.',450,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺450 / Double: ₺700"}'::jsonb,true,1430),

  -- Shots
  ('Guinness 52','Guinness 52',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1510),
  ('Hot Shot','Hot Shot',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1520),
  ('Snake Bite','Snake Bite',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1530),
  ('Kamikaze','Kamikaze',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1540),
  ('Big Bang','Big Bang',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1550),
  ('Blue Dragon (Signature)','Blue Dragon (Signature)','Vodka, Peach Liqueur, Apple Juice, Lemon Juice, Blue Curacao, Fresh Mint.','Vodka, Peach Liqueur, Apple Juice, Lemon Juice, Blue Curacao, Fresh Mint.',350,'shots',null,array['shot'],array['shot'],null,true,1560),
  ('Alabama Slammer','Alabama Slammer',null,null,350,'shots',null,array['shot'],array['shot'],null,true,1570),
  ('Olmeca Gold Tequila / Jameson / Jack Daniel''s / Jägermaister / Fireball','Olmeca Gold Tequila / Jameson / Jack Daniel''s / Jägermaister / Fireball',null,null,300,'shots',null,array['shot'],array['shot'],null,true,1580),

  -- Bar Bites
  ('French Fries','French Fries',null,null,370,'bar_bites',null,array['kitchen'],array['kitchen'],null,true,1710),
  ('Falafel','Falafel','Crispy falafel served with our signature sauce, salad and French fries.','Crispy falafel served with our signature sauce, salad and French fries.',540,'bar_bites',null,array['kitchen'],array['kitchen'],null,true,1720),
  ('Beer Basket','Beer Basket','A selection of onion rings, crispy cheese pastries, French fries and sausage. Perfect for sharing.','A selection of onion rings, crispy cheese pastries, French fries and sausage. Perfect for sharing.',590,'bar_bites',null,array['sharing'],array['sharing'],null,true,1730),
  ('Cheese Plate','Cheese Plate','A selection of cheeses served with seasonal fruits and nuts, perfect for pairing with your drink.','A selection of cheeses served with seasonal fruits and nuts, perfect for pairing with your drink.',690,'bar_bites',null,array['sharing'],array['sharing'],null,true,1740),
  ('Crispy Chicken','Crispy Chicken','Crispy chicken breast tenders served with onion rings and French fries.','Crispy chicken breast tenders served with onion rings and French fries.',590,'bar_bites',null,array['kitchen'],array['kitchen'],null,true,1750),

  -- House Specials
  ('Lionfish & Chips','Lionfish & Chips','Crispy tempura-fried lionfish served with our signature sauce, French fries and salad.','Crispy tempura-fried lionfish served with our signature sauce, French fries and salad.',990,'house_specials',null,array['house special'],array['house special'],null,true,1810),
  ('D.B. Burger','D.B. Burger','Juicy homemade burger on our homemade bun with cheddar, caramelized onions and crispy onion rings, served with French fries, lettuce, tomato and pickles.','Juicy homemade burger on our homemade bun with cheddar, caramelized onions and crispy onion rings, served with French fries, lettuce, tomato and pickles.',590,'house_specials',null,array['house special'],array['house special'],null,true,1820),
  ('100 g. Beef Sausage','100 g. Beef Sausage','100 g Aris Gurme beef sausage with Emmental Swiss cheese, served with French fries and onion rings.','100 g Aris Gurme beef sausage with Emmental Swiss cheese, served with French fries and onion rings.',890,'house_specials',null,array['house special'],array['house special'],null,true,1830),
  ('Chicken Wings (for 1)','Chicken Wings (for 1)','Juicy chicken wings marinated in our signature spicy sauce, served with French fries.','Juicy chicken wings marinated in our signature spicy sauce, served with French fries.',490,'house_specials',null,array['house special'],array['house special'],null,true,1840),
  ('Chicken Wings (for 2)','Chicken Wings (for 2)','Juicy chicken wings marinated in our signature spicy sauce, served with French fries.','Juicy chicken wings marinated in our signature spicy sauce, served with French fries.',790,'house_specials',null,array['house special'],array['house special'],null,true,1850);
