delete from public.menu_items;

insert into public.menu_items (
  name,
  name_en,
  description,
  description_en,
  price,
  category,
  image_url,
  tags,
  tags_en,
  details,
  is_available,
  sort_order
)
values
  -- Beers
  (
    'Efes Pilsen Draft',
    'Efes Pilsen Draft',
    'Draft beer. 33 cl: ₺175 / 50 cl: ₺250.',
    'Draft beer. 33 cl: ₺175 / 50 cl: ₺250.',
    175,
    'beers',
    null,
    array['draft'],
    array['draft'],
    '{"priceLabel":"33 cl: ₺175 / 50 cl: ₺250"}'::jsonb,
    true,
    10
  ),
  (
    'Efes Pilsen Take Away',
    'Efes Pilsen Take Away',
    'Take away draft. 40 cl: ₺190. Glass deposit: ₺10.',
    'Take away draft. 40 cl: ₺190. Glass deposit: ₺10.',
    190,
    'beers',
    null,
    array['take away'],
    array['take away'],
    '{"priceLabel":"40 cl: ₺190 / glass deposit: ₺10"}'::jsonb,
    true,
    20
  ),
  (
    'Efes Pilsen',
    'Efes Pilsen',
    'Bottle beer. 30 cl.',
    'Bottle beer. 30 cl.',
    250,
    'beers',
    null,
    array['bottle'],
    array['bottle'],
    '{"priceLabel":"30 cl: ₺250"}'::jsonb,
    true,
    30
  ),
  (
    'Efes Malt',
    'Efes Malt',
    'Bottle beer. 50 cl.',
    'Bottle beer. 50 cl.',
    320,
    'beers',
    null,
    array['bottle'],
    array['bottle'],
    '{"priceLabel":"50 cl: ₺320"}'::jsonb,
    true,
    40
  ),
  (
    'Efes Green',
    'Efes Green',
    'Bottle beer. 50 cl.',
    'Bottle beer. 50 cl.',
    320,
    'beers',
    null,
    array['bottle'],
    array['bottle'],
    '{"priceLabel":"50 cl: ₺320"}'::jsonb,
    true,
    50
  ),
  (
    'Efes Glutenfree',
    'Efes Glutenfree',
    'Bottle beer. 50 cl.',
    'Bottle beer. 50 cl.',
    330,
    'beers',
    null,
    array['gluten free'],
    array['gluten free'],
    '{"priceLabel":"50 cl: ₺330"}'::jsonb,
    true,
    60
  ),
  (
    'Bomonti Unfiltered',
    'Bomonti Unfiltered',
    'Bottle beer. 50 cl.',
    'Bottle beer. 50 cl.',
    410,
    'beers',
    null,
    array['unfiltered'],
    array['unfiltered'],
    '{"priceLabel":"50 cl: ₺410"}'::jsonb,
    true,
    70
  ),
  (
    'Becks',
    'Becks',
    'Bottle beer. 50 cl.',
    'Bottle beer. 50 cl.',
    350,
    'beers',
    null,
    array['lager'],
    array['lager'],
    '{"priceLabel":"50 cl: ₺350"}'::jsonb,
    true,
    80
  ),
  (
    'Bud',
    'Bud',
    'Bottle beer. 33 cl.',
    'Bottle beer. 33 cl.',
    320,
    'beers',
    null,
    array['lager'],
    array['lager'],
    '{"priceLabel":"33 cl: ₺320"}'::jsonb,
    true,
    90
  ),
  (
    'Stella',
    'Stella',
    'Bottle beer. 44 cl.',
    'Bottle beer. 44 cl.',
    370,
    'beers',
    null,
    array['lager'],
    array['lager'],
    '{"priceLabel":"44 cl: ₺370"}'::jsonb,
    true,
    100
  ),
  (
    'Corona',
    'Corona',
    'Bottle beer. 33 cl.',
    'Bottle beer. 33 cl.',
    410,
    'beers',
    null,
    array['lager'],
    array['lager'],
    '{"priceLabel":"33 cl: ₺410"}'::jsonb,
    true,
    110
  ),
  (
    'Gara Guzu Summer IPA',
    'Gara Guzu Summer IPA',
    'Bottle beer. 33 cl.',
    'Bottle beer. 33 cl.',
    495,
    'beers',
    null,
    array['ipa'],
    array['ipa'],
    '{"priceLabel":"33 cl: ₺495"}'::jsonb,
    true,
    120
  ),
  (
    'Duvel',
    'Duvel',
    'Bottle beer. 33 cl.',
    'Bottle beer. 33 cl.',
    650,
    'beers',
    null,
    array['strong ale'],
    array['strong ale'],
    '{"priceLabel":"33 cl: ₺650"}'::jsonb,
    true,
    130
  ),
  (
    'Peja (Alcoholfree)',
    'Peja (Alcoholfree)',
    'Alcohol-free beer. 33 cl.',
    'Alcohol-free beer. 33 cl.',
    190,
    'beers',
    null,
    array['alcohol free'],
    array['alcohol free'],
    '{"priceLabel":"33 cl: ₺190"}'::jsonb,
    true,
    140
  ),

  -- Non Alcoholics
  ('Coca Cola','Coca Cola','33 cl.','33 cl.',140,'non_alcoholics',null,array['soft drink'],array['soft drink'],'{"priceLabel":"33 cl: ₺140"}'::jsonb,true,210),
  ('Coca Cola Zero','Coca Cola Zero','33 cl.','33 cl.',140,'non_alcoholics',null,array['soft drink'],array['soft drink'],'{"priceLabel":"33 cl: ₺140"}'::jsonb,true,220),
  ('Sprite','Sprite','33 cl.','33 cl.',140,'non_alcoholics',null,array['soft drink'],array['soft drink'],'{"priceLabel":"33 cl: ₺140"}'::jsonb,true,230),
  ('Schweppes Tonic','Schweppes Tonic','25 cl.','25 cl.',100,'non_alcoholics',null,array['mixer'],array['mixer'],'{"priceLabel":"25 cl: ₺100"}'::jsonb,true,240),
  ('Sparkling Water','Sparkling Water','20 cl.','20 cl.',75,'non_alcoholics',null,array['water'],array['water'],'{"priceLabel":"20 cl: ₺75"}'::jsonb,true,250),
  ('Bottled Water','Bottled Water','33 cl.','33 cl.',75,'non_alcoholics',null,array['water'],array['water'],'{"priceLabel":"33 cl: ₺75"}'::jsonb,true,260),
  ('Cappy Fruit Juices','Cappy Fruit Juices',null,null,140,'non_alcoholics',null,array['juice'],array['juice'],null,true,270),
  ('Fresh Orange Juice','Fresh Orange Juice',null,null,190,'non_alcoholics',null,array['fresh'],array['fresh'],null,true,280),
  ('Homemade Ice Tea (peach)','Homemade Ice Tea (peach)',null,null,190,'non_alcoholics',null,array['homemade'],array['homemade'],null,true,290),
  ('Homemade Lemonade','Homemade Lemonade',null,null,230,'non_alcoholics',null,array['homemade'],array['homemade'],null,true,300),

  -- Coffee
  ('Espresso','Espresso',null,null,90,'coffee',null,array['coffee'],array['coffee'],null,true,410),
  ('Double Espresso','Double Espresso',null,null,160,'coffee',null,array['coffee'],array['coffee'],null,true,420),
  ('Americano','Americano',null,null,200,'coffee',null,array['coffee'],array['coffee'],null,true,430),
  ('Cappuccino','Cappuccino',null,null,220,'coffee',null,array['coffee'],array['coffee'],null,true,440),
  ('Latte','Latte',null,null,220,'coffee',null,array['coffee'],array['coffee'],null,true,450),
  ('Turkish Coffee','Turkish Coffee',null,null,120,'coffee',null,array['coffee'],array['coffee'],null,true,460),
  ('Irish Coffee (with Jameson)','Irish Coffee (with Jameson)',null,null,460,'coffee',null,array['coffee'],array['coffee'],null,true,470),

  -- Wines
  (
    'Turasan Bağdan White',
    'Turasan Bağdan White',
    'Emir. It has a fresh, crisp taste with notes of green apple, citrus, and a light mineral finish.',
    'Emir. It has a fresh, crisp taste with notes of green apple, citrus, and a light mineral finish.',
    250,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"Glass: ₺250 / 70 cl: ₺900"}'::jsonb,
    true,
    510
  ),
  (
    'Vinkara Quattro White',
    'Vinkara Quattro White',
    'Narince, Hasandede and Emir. Fruity, rich and easy drinking with a strong acidity.',
    'Narince, Hasandede and Emir. Fruity, rich and easy drinking with a strong acidity.',
    300,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"Glass: ₺300 / 70 cl: ₺1100"}'::jsonb,
    true,
    520
  ),
  (
    'Paşaeli SYS White',
    'Paşaeli SYS White',
    'Sultaniye, Yapıncak and Sıdalan. 3 months rest. On the nose lemon, green apple and honeysuckle. Medium acidity, high minerality, with flavours of daisy, apple and yellow plum.',
    'Sultaniye, Yapıncak and Sıdalan. 3 months rest. On the nose lemon, green apple and honeysuckle. Medium acidity, high minerality, with flavours of daisy, apple and yellow plum.',
    1950,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"70 cl: ₺1950"}'::jsonb,
    true,
    530
  ),
  (
    'Porta Diverti Sauvignon Blanc',
    'Porta Diverti Sauvignon Blanc',
    'Scents of minerals and citrus. Very crisp and fruity on the palate with a lengthy finish.',
    'Scents of minerals and citrus. Very crisp and fruity on the palate with a lengthy finish.',
    2750,
    'wines',
    null,
    array['white'],
    array['white'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    540
  ),
  (
    'Turasan Bağdan Rose',
    'Turasan Bağdan Rose',
    'Cappadocia, Turkey, with notes of strawberry, raspberry, and a hint of citrus.',
    'Cappadocia, Turkey, with notes of strawberry, raspberry, and a hint of citrus.',
    250,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"Glass: ₺250 / 70 cl: ₺900"}'::jsonb,
    true,
    550
  ),
  (
    'Vinkara Quattro Rose',
    'Vinkara Quattro Rose',
    'Kalecik Karası and Aleatico. Dry with scents of rose and lime from the Aleatico and lively flavours of red fruits such as strawberry, cherry as well as hints of grapefruit, mango and kiwi.',
    'Kalecik Karası and Aleatico. Dry with scents of rose and lime from the Aleatico and lively flavours of red fruits such as strawberry, cherry as well as hints of grapefruit, mango and kiwi.',
    300,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"Glass: ₺300 / 70 cl: ₺1100"}'::jsonb,
    true,
    560
  ),
  (
    'Paşaeli Çalkarası Blush',
    'Paşaeli Çalkarası Blush',
    'Çalkarası. Fermented in stainless steel tanks and aged on the lees for 3 months. On the nose wild strawberry, raspberry and thyme. On the palate light bodied with a refreshing acidity, strawberry, raspberry, red cherry, pink grapefruit.',
    'Çalkarası. Fermented in stainless steel tanks and aged on the lees for 3 months. On the nose wild strawberry, raspberry and thyme. On the palate light bodied with a refreshing acidity, strawberry, raspberry, red cherry, pink grapefruit.',
    1950,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"70 cl: ₺1950"}'::jsonb,
    true,
    570
  ),
  (
    'Porta Diverti Rose',
    'Porta Diverti Rose',
    'Merlot. Fermented in steel tanks. Scents of red fruits and rose jam. Lively with a rich, long finish.',
    'Merlot. Fermented in steel tanks. Scents of red fruits and rose jam. Lively with a rich, long finish.',
    2750,
    'wines',
    null,
    array['rose'],
    array['rose'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    580
  ),
  (
    'Turasan Peri Bacasi Red',
    'Turasan Peri Bacasi Red',
    'A smooth and approachable red wine from Cappadocia, Turkey, with flavors of red berries, plum, and subtle spices. Medium-bodied with soft tannins.',
    'A smooth and approachable red wine from Cappadocia, Turkey, with flavors of red berries, plum, and subtle spices. Medium-bodied with soft tannins.',
    250,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"Glass: ₺250 / 70 cl: ₺900"}'::jsonb,
    true,
    590
  ),
  (
    'Vinkara Quattro Red',
    'Vinkara Quattro Red',
    'Öküzgözü, Boğazkere and Alicante. On the nose plum, cherry and pepper. Dry, with mild tannins and a long finish.',
    'Öküzgözü, Boğazkere and Alicante. On the nose plum, cherry and pepper. Dry, with mild tannins and a long finish.',
    300,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"Glass: ₺300 / 70 cl: ₺1100"}'::jsonb,
    true,
    600
  ),
  (
    'Paşaeli CSKS Red',
    'Paşaeli CSKS Red',
    'Cabernet Sauvignon and Karasakız, from around 25 years old vines. Aged in oak barrels for 3 months. On the nose sour cherry and bramble. On the palate soft tannins, black pepper, sour cherry, mint and tobacco.',
    'Cabernet Sauvignon and Karasakız, from around 25 years old vines. Aged in oak barrels for 3 months. On the nose sour cherry and bramble. On the palate soft tannins, black pepper, sour cherry, mint and tobacco.',
    1950,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"70 cl: ₺1950"}'::jsonb,
    true,
    610
  ),
  (
    'Porta Diverti Red',
    'Porta Diverti Red',
    'Cabernet Sauvignon, Cabernet Franc, Merlot and Petit Verdot. Aged in oak barrels. Limited filtration. On the nose ripe fruits, tobacco and chocolate. On the palate fruity and vivid with complex flavours. Soft and easy drinking.',
    'Cabernet Sauvignon, Cabernet Franc, Merlot and Petit Verdot. Aged in oak barrels. Limited filtration. On the nose ripe fruits, tobacco and chocolate. On the palate fruity and vivid with complex flavours. Soft and easy drinking.',
    2750,
    'wines',
    null,
    array['red'],
    array['red'],
    '{"priceLabel":"70 cl: ₺2750"}'::jsonb,
    true,
    620
  ),

  -- Signatures
  ('Garden Fairy','Garden Fairy','Smirnoff Vodka, Sour Apple Liqueur, Sour Apple Juice, Lemon Juice, Mint Mixer, Fresh Mint.','Smirnoff Vodka, Sour Apple Liqueur, Sour Apple Juice, Lemon Juice, Mint Mixer, Fresh Mint.',750,'signatures',null,array['signature'],array['signature'],null,true,710),
  ('Jamal Libre','Jamal Libre','C. Morgan Spiced Rum, Coke, Muddled Lime.','C. Morgan Spiced Rum, Coke, Muddled Lime.',750,'signatures',null,array['signature'],array['signature'],null,true,720),
  ('Our Garden''s Sorrel','Our Garden''s Sorrel','Beefeater Gin, Special Sorrel Mix.','Beefeater Gin, Special Sorrel Mix.',800,'signatures',null,array['signature'],array['signature'],null,true,730),
  ('Botanique','Botanique','Beefeater Gin, Basil Mix, Lemon Juice, Cucumber, Rosemary.','Beefeater Gin, Basil Mix, Lemon Juice, Cucumber, Rosemary.',800,'signatures',null,array['signature'],array['signature'],null,true,740),
  ('Sour Almond','Sour Almond','Disoranno, Jack Daniel''s, Lemon Juice.','Disoranno, Jack Daniel''s, Lemon Juice.',800,'signatures',null,array['signature'],array['signature'],null,true,750),

  -- Cocktails
  ('Gin Fizz','Gin Fizz','Beefeater Gin, Lemon Juice, Simple Syrup, Club Soda, Powdered Sugar.','Beefeater Gin, Lemon Juice, Simple Syrup, Club Soda, Powdered Sugar.',600,'cocktails',null,array['classic'],array['classic'],null,true,810),
  ('Million Dollar','Million Dollar','Beefeater Gin, Martini Rosso, Pineapple Juice, Lemon Juice.','Beefeater Gin, Martini Rosso, Pineapple Juice, Lemon Juice.',600,'cocktails',null,array['classic'],array['classic'],null,true,820),
  ('Green Ghost','Green Ghost','Beefeater Gin, Green Chartreuse, Lime Juice.','Beefeater Gin, Green Chartreuse, Lime Juice.',750,'cocktails',null,array['classic'],array['classic'],null,true,830),
  ('The Jasmine','The Jasmine','Beefeater Gin, Campari, Cointreau, Lemon Juice.','Beefeater Gin, Campari, Cointreau, Lemon Juice.',750,'cocktails',null,array['classic'],array['classic'],null,true,840),
  ('Negroni','Negroni','Beefeater Gin, Campari, Martini Rosso.','Beefeater Gin, Campari, Martini Rosso.',750,'cocktails',null,array['classic'],array['classic'],null,true,850),
  ('Cosmopolitan','Cosmopolitan','Smirnoff Vodka, Cointreau, Cranberry Juice, Lemon Juice.','Smirnoff Vodka, Cointreau, Cranberry Juice, Lemon Juice.',750,'cocktails',null,array['classic'],array['classic'],null,true,860),
  ('Porn Star Martini','Porn Star Martini','Absolut Vanilla, Passoã, Passion Fruit Puree, Lime Juice. Prosecco on the side.','Absolut Vanilla, Passoã, Passion Fruit Puree, Lime Juice. Prosecco on the side.',750,'cocktails',null,array['martini'],array['martini'],null,true,870),
  ('Espresso Martini','Espresso Martini','Smirnoff Vodka, Kahlua, Espresso.','Smirnoff Vodka, Kahlua, Espresso.',750,'cocktails',null,array['martini'],array['martini'],null,true,880),
  ('Bloody Mary','Bloody Mary','Smirnoff Vodka, Tomato Juice, Lemon Juice, Tabasco, Worcestershire Sauce, Salt, Black Pepper, Celery.','Smirnoff Vodka, Tomato Juice, Lemon Juice, Tabasco, Worcestershire Sauce, Salt, Black Pepper, Celery.',750,'cocktails',null,array['classic'],array['classic'],null,true,890),
  ('Mojito','Mojito','Havana Club Rum, Club Soda, Lime, Brown Sugar, Fresh Mint.','Havana Club Rum, Club Soda, Lime, Brown Sugar, Fresh Mint.',700,'cocktails',null,array['classic'],array['classic'],null,true,900),
  ('Strawberry Daiquiri (Frozen)','Strawberry Daiquiri (Frozen)','Havana Club Rum, Fresh Strawberries, Strawberry Puree, Lime Juice.','Havana Club Rum, Fresh Strawberries, Strawberry Puree, Lime Juice.',700,'cocktails',null,array['frozen'],array['frozen'],null,true,910),
  ('Bahama Mama','Bahama Mama','C. Morgan Spiced Rum, Malibu, Pineapple Juice, Orange Juice, Grenadine.','C. Morgan Spiced Rum, Malibu, Pineapple Juice, Orange Juice, Grenadine.',750,'cocktails',null,array['tropical'],array['tropical'],null,true,920),
  ('Margarita','Margarita','Sierra Silver Tequila, Cointreau, Lemon Juice, Lime Juice, Salt.','Sierra Silver Tequila, Cointreau, Lemon Juice, Lime Juice, Salt.',750,'cocktails',null,array['classic'],array['classic'],null,true,930),
  ('Chili Passion Margarita','Chili Passion Margarita','Sierra Silver Tequila, Cointreau, Passion Fruit Puree, Lime Juice, Tabasco.','Sierra Silver Tequila, Cointreau, Passion Fruit Puree, Lime Juice, Tabasco.',750,'cocktails',null,array['spicy'],array['spicy'],null,true,940),
  ('Whiskey Sour','Whiskey Sour','Jim Beam, Lemon Juice, Brown Sugar.','Jim Beam, Lemon Juice, Brown Sugar.',850,'cocktails',null,array['classic'],array['classic'],null,true,950),
  ('Old Fashioned','Old Fashioned','Jim Beam, Brown Sugar, Angostura Bitters.','Jim Beam, Brown Sugar, Angostura Bitters.',850,'cocktails',null,array['classic'],array['classic'],null,true,960),
  ('Boulevardier','Boulevardier','Jim Beam, Campari, Martini Rosso.','Jim Beam, Campari, Martini Rosso.',850,'cocktails',null,array['classic'],array['classic'],null,true,970),

  -- Spritzes
  ('Aperol Spritz','Aperol Spritz','Aperol, Prosecco, Club Soda.','Aperol, Prosecco, Club Soda.',650,'spritzes',null,array['spritz'],array['spritz'],null,true,1010),
  ('Garden Spritz','Garden Spritz','Martini Bianco, Prosecco, Lime Mixer, Fresh Mint.','Martini Bianco, Prosecco, Lime Mixer, Fresh Mint.',650,'spritzes',null,array['spritz'],array['spritz'],null,true,1020),
  ('Campari Spritz','Campari Spritz','Campari, Prosecco, Club Soda.','Campari, Prosecco, Club Soda.',650,'spritzes',null,array['spritz'],array['spritz'],null,true,1030),
  ('Limoncello Spritz','Limoncello Spritz','Limonchello, Prosecco, Club Soda.','Limonchello, Prosecco, Club Soda.',650,'spritzes',null,array['spritz'],array['spritz'],null,true,1040),
  ('Hugo','Hugo','Elderflower Liqueur, Prosecco, Club Soda.','Elderflower Liqueur, Prosecco, Club Soda.',700,'spritzes',null,array['spritz'],array['spritz'],null,true,1050),

  -- Spirits
  ('Gordon''s','Gordon''s','Gin.','Gin.',260,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺260 / Double: ₺390"}'::jsonb,true,1110),
  ('Beefeater','Beefeater','Gin.','Gin.',310,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺310 / Double: ₺470"}'::jsonb,true,1120),
  ('Bombay Sapphire','Bombay Sapphire','Gin.','Gin.',410,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺410 / Double: ₺630"}'::jsonb,true,1130),
  ('Hendrick''s','Hendrick''s','Gin.','Gin.',610,'spirits',null,array['gin'],array['gin'],'{"priceLabel":"Single: ₺610 / Double: ₺960"}'::jsonb,true,1140),
  ('Smirnoff','Smirnoff','Vodka.','Vodka.',260,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺260 / Double: ₺390"}'::jsonb,true,1150),
  ('Absolut','Absolut','Vodka.','Vodka.',310,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺310 / Double: ₺490"}'::jsonb,true,1160),
  ('Belvedere','Belvedere','Vodka.','Vodka.',610,'spirits',null,array['vodka'],array['vodka'],'{"priceLabel":"Single: ₺610 / Double: ₺960"}'::jsonb,true,1170),
  ('C. Morgan Spiced','C. Morgan Spiced','Rum.','Rum.',260,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺260 / Double: ₺390"}'::jsonb,true,1180),
  ('Negrita Dark','Negrita Dark','Rum.','Rum.',260,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺260 / Double: ₺390"}'::jsonb,true,1190),
  ('Havana Club 3 Años','Havana Club 3 Años','Rum.','Rum.',340,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1200),
  ('Zacapa','Zacapa','Rum.','Rum.',510,'spirits',null,array['rum'],array['rum'],'{"priceLabel":"Single: ₺510 / Double: ₺810"}'::jsonb,true,1210),
  ('Sierra Blanco','Sierra Blanco','Tequila.','Tequila.',290,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺290 / Double: ₺440"}'::jsonb,true,1220),
  ('Olmeca Gold','Olmeca Gold','Tequila.','Tequila.',310,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺310 / Double: ₺490"}'::jsonb,true,1230),
  ('Don Julio Blanco','Don Julio Blanco','Tequila.','Tequila.',540,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺540 / Double: ₺840"}'::jsonb,true,1240),
  ('Patron Reposado','Patron Reposado','Tequila.','Tequila.',630,'spirits',null,array['tequila'],array['tequila'],'{"priceLabel":"Single: ₺630 / Double: ₺990"}'::jsonb,true,1250),
  ('Jim Beam','Jim Beam','Whiskey.','Whiskey.',310,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺310 / Double: ₺490"}'::jsonb,true,1260),
  ('Jack Daniel''s','Jack Daniel''s','Whiskey.','Whiskey.',340,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1270),
  ('Jameson','Jameson','Whiskey.','Whiskey.',340,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1280),
  ('Famous Grouse','Famous Grouse','Whiskey.','Whiskey.',290,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺290 / Double: ₺440"}'::jsonb,true,1290),
  ('Johnnie Walker Black Label','Johnnie Walker Black Label','Whiskey.','Whiskey.',340,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1300),
  ('Glenfiddich 12','Glenfiddich 12','Whiskey.','Whiskey.',590,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺590 / Double: ₺920"}'::jsonb,true,1310),
  ('Talisker','Talisker','Whiskey.','Whiskey.',630,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺630 / Double: ₺990"}'::jsonb,true,1320),
  ('Lagavulin','Lagavulin','Whiskey.','Whiskey.',630,'spirits',null,array['whiskey'],array['whiskey'],'{"priceLabel":"Single: ₺630 / Double: ₺990"}'::jsonb,true,1330),
  ('Napoleon Apollon','Napoleon Apollon','Brandy.','Brandy.',320,'spirits',null,array['brandy'],array['brandy'],'{"priceLabel":"Single: ₺320 / Double: ₺400"}'::jsonb,true,1340),
  ('Metaxa 7 Stars','Metaxa 7 Stars','Brandy.','Brandy.',430,'spirits',null,array['brandy'],array['brandy'],'{"priceLabel":"Single: ₺430 / Double: ₺690"}'::jsonb,true,1350),
  ('Hennessy VS','Hennessy VS','Cognac.','Cognac.',410,'spirits',null,array['cognac'],array['cognac'],'{"priceLabel":"Single: ₺410 / Double: ₺640"}'::jsonb,true,1360),
  ('Rémy Martin VSOP','Rémy Martin VSOP','Cognac.','Cognac.',750,'spirits',null,array['cognac'],array['cognac'],'{"priceLabel":"Single: ₺750 / Double: ₺1190"}'::jsonb,true,1370),
  ('Baileys','Baileys','Liqueur.','Liqueur.',240,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺240 / Double: ₺360"}'::jsonb,true,1380),
  ('Archers','Archers','Liqueur.','Liqueur.',310,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺310 / Double: ₺490"}'::jsonb,true,1390),
  ('Cointreau','Cointreau','Liqueur.','Liqueur.',430,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺430 / Double: ₺690"}'::jsonb,true,1400),
  ('Martini Bianco','Martini Bianco','Liqueur.','Liqueur.',310,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺310 / Double: ₺470"}'::jsonb,true,1410),
  ('Disaronno','Disaronno','Liqueur.','Liqueur.',340,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1420),
  ('Göbek Rakı','Göbek Rakı','Liqueur.','Liqueur.',340,'spirits',null,array['liqueur'],array['liqueur'],'{"priceLabel":"Single: ₺340 / Double: ₺520"}'::jsonb,true,1430),

  -- Shots
  ('Guiness 52','Guiness 52','Kahlua, Baileys, Guiness.','Kahlua, Baileys, Guiness.',290,'shots',null,array['shot'],array['shot'],null,true,1510),
  ('Hot Shot','Hot Shot','Galliano, Coffee, Cream.','Galliano, Coffee, Cream.',290,'shots',null,array['shot'],array['shot'],null,true,1520),
  ('Blue Dragon (Signature)','Blue Dragon (Signature)','Vodka, Peach Liqueur, Apple Juice, Lemon Juice, Blue Curacao Mixer, Fresh Mint.','Vodka, Peach Liqueur, Apple Juice, Lemon Juice, Blue Curacao Mixer, Fresh Mint.',290,'shots',null,array['shot'],array['shot'],null,true,1530),
  ('Snake Bite','Snake Bite','Jack Honey, Lime mixer.','Jack Honey, Lime mixer.',290,'shots',null,array['shot'],array['shot'],null,true,1540),
  ('Kamikaze','Kamikaze','Vodka, Triple Sec, Lime Mixer.','Vodka, Triple Sec, Lime Mixer.',290,'shots',null,array['shot'],array['shot'],null,true,1550),
  ('Alabama Slammer','Alabama Slammer','Gin, Amaretto, Southern Comfort, Cranberry Juice, Lemon Juice.','Gin, Amaretto, Southern Comfort, Cranberry Juice, Lemon Juice.',290,'shots',null,array['shot'],array['shot'],null,true,1560),
  ('Big Bang','Big Bang','White Rum, Drak Rum, TripleSec, Orange Juice, Pineapple Juice, Angostura.','White Rum, Drak Rum, TripleSec, Orange Juice, Pineapple Juice, Angostura.',290,'shots',null,array['shot'],array['shot'],null,true,1570),
  ('Olmeca Gold Tequila','Olmeca Gold Tequila',null,null,250,'shots',null,array['tequila'],array['tequila'],null,true,1580),
  ('Jameson / Jack Daniel''s Whiskey','Jameson / Jack Daniel''s Whiskey',null,null,290,'shots',null,array['whiskey'],array['whiskey'],null,true,1590),
  ('Jägermaister','Jägermaister',null,null,290,'shots',null,array['liqueur'],array['liqueur'],null,true,1600),
  ('Fireball','Fireball',null,null,290,'shots',null,array['liqueur'],array['liqueur'],null,true,1610),

  -- Bar Bites
  ('French Fries','French Fries','1/2 kg.','1/2 kg.',320,'bar_bites',null,array['kitchen'],array['kitchen'],'{"priceLabel":"1/2 kg: ₺320"}'::jsonb,true,1710),
  ('Falafel','Falafel','Crispy falafel served with our signature sauce, salad and French fries.','Crispy falafel served with our signature sauce, salad and French fries.',490,'bar_bites',null,array['kitchen'],array['kitchen'],null,true,1720),
  ('Beer Basket','Beer Basket','A selection of onion rings, crispy cheese pastries, French fries and sausage. Perfect for sharing.','A selection of onion rings, crispy cheese pastries, French fries and sausage. Perfect for sharing.',590,'bar_bites',null,array['sharing'],array['sharing'],null,true,1730),
  ('Cheese Plate','Cheese Plate','A selection of cheeses served with seasonal fruits and nuts, perfect for pairing with your drink.','A selection of cheeses served with seasonal fruits and nuts, perfect for pairing with your drink.',690,'bar_bites',null,array['sharing'],array['sharing'],null,true,1740),
  ('Crispy Chicken','Crispy Chicken','Crispy chicken breast tenders served with onion rings and French fries.','Crispy chicken breast tenders served with onion rings and French fries.',490,'bar_bites',null,array['kitchen'],array['kitchen'],null,true,1750),

  -- House Specials
  ('Lionfish & Chips','Lionfish & Chips','Crispy tempura-fried lionfish served with our signature sauce, French fries and salad.','Crispy tempura-fried lionfish served with our signature sauce, French fries and salad.',980,'house_specials',null,array['house special'],array['house special'],null,true,1810),
  ('D.B. Burger','D.B. Burger','Juicy homemade burger on our homemade bun with cheddar, caramelized onions and crispy onion rings, served with French fries, lettuce, tomato and pickles.','Juicy homemade burger on our homemade bun with cheddar, caramelized onions and crispy onion rings, served with French fries, lettuce, tomato and pickles.',560,'house_specials',null,array['house special'],array['house special'],null,true,1820),
  ('100 g. Beef Sausage','100 g. Beef Sausage','100 g Aris Gurme beef sausage with Emmental Swiss cheese, served with French fries and onion rings.','100 g Aris Gurme beef sausage with Emmental Swiss cheese, served with French fries and onion rings.',890,'house_specials',null,array['house special'],array['house special'],null,true,1830),
  ('Chicken Wings (for 1)','Chicken Wings (for 1)','Juicy chicken wings marinated in our signature spicy sauce.','Juicy chicken wings marinated in our signature spicy sauce.',450,'house_specials',null,array['house special'],array['house special'],null,true,1840),
  ('Chicken Wings (for 2)','Chicken Wings (for 2)','Juicy chicken wings marinated in our signature spicy sauce.','Juicy chicken wings marinated in our signature spicy sauce.',790,'house_specials',null,array['house special'],array['house special'],null,true,1850);
